CREATE TABLE IF NOT EXISTS METADATA_JSON_STRUCTURE (
    FIELD_NAME STRING,
    JSON_PATH STRING,
    DATA_TYPE STRING,
    NESTING_LEVEL NUMBER,
    UPDATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS METADATA_TABLE_DEFINITION (
    TARGET_TABLE STRING,
    TARGET_COLUMN STRING,
    JSON_PATH STRING,
    DATA_TYPE STRING,
    IS_MANDATORY STRING,
    ACTIVE_FLAG STRING DEFAULT 'Y',
    UPDATED_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS METADATA_SCHEMA_CHANGES (
    FIELD_NAME STRING,
    JSON_PATH STRING,
    CHANGE_TYPE STRING,
    OLD_VALUE STRING,
    NEW_VALUE STRING,
    PROCESSED_FLAG STRING DEFAULT 'N',
    CHANGE_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS AUDIT_LOG (
    --RUN_ID STRING,
    FILE_NAME STRING,
    STG_COUNT NUMBER,
    CUSTOMER_CNT NUMBER,
    ORDERS_CNT NUMBER,
    ITEMS_CNT NUMBER,
    STATUS STRING,
    ERROR_COUNT NUMBER,
    START_TIME TIMESTAMP,
    END_TIME TIMESTAMP,
    COMMENTS STRING
);
