CREATE OR REPLACE PROCEDURE SP_RUN_PIPELINE()
RETURNS STRING
LANGUAGE SQL
AS
$$
DECLARE
    v_run_id STRING DEFAULT UUID_STRING();
BEGIN
    CALL SP_LOAD_DATA();
    CALL SP_READ_JSON_METADATA();
    CALL SP_VALIDATE_SCHEMA();
    CALL SP_LOAD_CUSTOMER();
    CALL SP_LOAD_ORDERS();
    CALL SP_LOAD_ORDER_ITEMS();
    CALL SP_AUDIT(v_run_id);
    RETURN 'PIPELINE COMPLETE | RUN_ID=' || v_run_id;
END;
$$;
