CREATE OR REPLACE TABLE LANDING_JSON (
    RAW VARIANT,
    FILE_NAME STRING,
    LOAD_TS TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS CUSTOMER (
    ID          INTEGER,
    NAME        STRING,
    EMAIL       STRING,
    AGE         INTEGER,
    IS_ACTIVE   BOOLEAN,
    SIGNUP_DATE DATE,
    STREET      STRING,
    CITY        STRING,
    STATE       STRING,
    ZIP         STRING
);

CREATE TABLE IF NOT EXISTS  ORDERS (
    CUSTOMER_ID INTEGER,
    ORDER_ID    STRING,
    AMOUNT      NUMBER(10,2),
    ORDER_DATE  DATE
);

CREATE TABLE  IF NOT EXISTS  ORDER_ITEMS (
    CUSTOMER_ID INTEGER,
    ORDER_ID    STRING,
    ITEM_NAME   STRING
);
